// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGajuteVxzfv6iYz2bmZXkbaRw2W44e2U',
    appId: '1:910822533:web:cd1264c4ba4e45e2696dec',
    messagingSenderId: '910822533',
    projectId: 'unuseful-project',
    authDomain: 'unuseful-project.firebaseapp.com',
    storageBucket: 'unuseful-project.appspot.com',
    measurementId: 'G-5X2SS6JCS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2poLYcmEc92PUYBjEyPxPqRqbeqrlxTY',
    appId: '1:910822533:android:173a52d5c4dcd3f3696dec',
    messagingSenderId: '910822533',
    projectId: 'unuseful-project',
    storageBucket: 'unuseful-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG4z4jBfu9JadRaWxPjri17d1ha0HlMhQ',
    appId: '1:910822533:ios:466e607ce1f4cb26696dec',
    messagingSenderId: '910822533',
    projectId: 'unuseful-project',
    storageBucket: 'unuseful-project.appspot.com',
    iosClientId: '910822533-6vitiiva875qrm79ggdktsogojnkhsb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.unuseful',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG4z4jBfu9JadRaWxPjri17d1ha0HlMhQ',
    appId: '1:910822533:ios:466e607ce1f4cb26696dec',
    messagingSenderId: '910822533',
    projectId: 'unuseful-project',
    storageBucket: 'unuseful-project.appspot.com',
    iosClientId: '910822533-6vitiiva875qrm79ggdktsogojnkhsb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.unuseful',
  );
}
